/**
 * Migration Map Generator
 *
 * Generates compile-time migration map for ASAR compatibility.
 * Reads migration files from src/main/database/migrations/ and
 * creates a TypeScript file with embedded migration references.
 *
 * This ensures migrations work in ASAR archives where fs.readdirSync
 * cannot access bundled files.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MIGRATIONS_DIR = path.join(__dirname, '..', 'src', 'main', 'database', 'migrations');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'main', 'database', 'migrations.generated.ts');

interface MigrationInfo {
  name: string;
  fileName: string;
}

function discoverMigrations(): MigrationInfo[] {
  try {
    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFiles = files
      .filter((file) => /^\d{14}_.*\.ts$/.test(file))
      .sort()
      .map((fileName) => ({
        name: fileName.replace(/\.ts$/, ''),
        fileName,
      }));
    return migrationFiles;
  } catch (error) {
    console.error(`Failed to read migrations directory: ${error}`);
    return [];
  }
}

function generateMigrationsFile(migrations: MigrationInfo[]): string {
  const imports = migrations
    .map((m, index) => `import * as migration${index} from './migrations/${m.name}';`)
    .join('\n');

  const mapEntries = migrations
    .map((m, index) => `  '${m.name}': migration${index},`)
    .join('\n');

  return `/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-migrations-map.ts
 * during the build process. It provides compile-time migration discovery
 * for ASAR archive compatibility.
 */

${imports}

export interface Migration {
  up: (knex: any) => Promise<void>;
  down?: (knex: any) => Promise<void>;
}

export const MIGRATIONS_MAP: Record<string, Migration> = {
${mapEntries}
};

export const MIGRATION_NAMES: string[] = [
${migrations.map((m) => `  '${m.name}',`).join('\n')}
];
`;
}

function main(): void {
  console.log('Generating migration map...');
  console.log(`Reading from: ${MIGRATIONS_DIR}`);

  const migrations = discoverMigrations();

  if (migrations.length === 0) {
    console.warn('No migrations found!');
  } else {
    console.log(`Found ${migrations.length} migration(s):`);
    migrations.forEach((m) => console.log(`  - ${m.name}`));
  }

  const content = generateMigrationsFile(migrations);

  fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log(`Generated: ${OUTPUT_FILE}`);
}

main();
